version: '3.7'

services:
  bitstamp: &btc_monitor
    image: leandro2r/btc_monitor:latest-python
    privileged: true
    devices:
      - /dev/snd:/dev/snd
    # volumes:
    #   - ./python:/home/btc_monitor
    #   - ./python/extras/btc_monitor:/etc/btc_monitor
    # entrypoint: "tail -f /dev/null"
    command: ["-v", "1000", "-a", "-m"]

  foxbit:
    <<: *btc_monitor
    environment:
      - API=http://watcher.foxbit.com.br/api/Ticker?exchange=Foxbit
      - BTC=0
      - TRADE_FEE=0
      - COLOR_ID=white
    command: ["-v", "10000", "-a"]

  shell:
    <<: *btc_monitor
    image: leandro2r/btc_monitor:latest-shell
    volumes:
      - ./shell:/home/btc_monitor
      - ./shell/extras/btc_monitor:/etc/btc_monitor
    # command: ["-v", "1000", "-a", "-c", "red"]
