name: Python application

on:
  push:
    paths:
      - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd python && pip install .[dev]

    - name: Lint with flake8
      run: |
        flake8 . --count --ignore=E402 --show-source --statistics
        flake8 . --count --ignore=E402 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
